language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'

before_install:
  - 'travis_retry sudo apt-get install python-dev libxml2-dev libxmlsec1-dev'
  - 'travis_retry pip install Cython --use-mirrors'

install:
  - 'travis_retry pip install -e ".[test]" --use-mirrors'
  - 'travis_retry pip install coveralls --use-mirrors'

script: 'py.test --pep8 --flakes --cov saml'

after_success: 'coveralls'
